# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f4dbbcac9fa2b7e0c52bd61201c8dad7baa9b98eecfb5ed18692a903a3e89d738df88a4297af59fef4addcd2f6d3a20c90cee8b92e76f3cc6d0b0c45b846576

test:
  secret_key_base: 2eaa8e25eeac79d41b17a94c85f161e8a44286929b6b718af0d58ef63fa41f1f2fb9b49bfdf8321b7d99530acdad2ca82ec01c56a661e8b24e54d0ca3d903691

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
